version: 2

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd src && npm install
      - persist_to_workspace:
          root: src
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cd src && npm run build
      - persist_to_workspace:
          root: src
          paths:
            - dist

  lint:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cd src && npm run lint

  unit-tests:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cd src && npm run test

workflows:
  version: 2
  build-and-validate:
    jobs:
      - install-dependencies:
          context: discpath
      - build:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
