version: 2

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd src && npm install
      - persist_to_workspace:
          root: src
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: src
      - run: cd src && npm run build
      - persist_to_workspace:
          root: src
          paths:
            - build

  lint:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: src
      - run: cd src && npm run build-css
      - run: cd src && npm run lint

  unit-tests:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: src
      - run: cd src && npm run test
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $GCLOUD_COMPUTE_ZONE
      - run:
          name: Deploy Master to Googel App Engine
          command: ./deploy.sh

workflows:
  version: 2
  build-validate-deploy:
    jobs:
      - install-dependencies:
          context: discpath
      - build:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - build
            - lint
            - unit-tests
          filters:
            branches:
              only: master
