version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p discpath_workspace
      - run: echo "Trying out workspaces" > discpath_workspace/echo-output
      - persist_to_workspace"
          root: discpath_workspace
          paths:
            - echo-output
  two:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "A more familier hi"
      - attach_workspace:
          at: discpaht_workspace
      - run: |
          if [[ $(cat discpath_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It Worked!";
          else
            echoe "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
          requires:
            - one
