version: 2

jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-8.11.3-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          - v1-dependencies-8.11.3-{{ .Environment.CIRCLE_BRANCH }}-
          - v1-dependencies-8.11.3-

      - run: cd src && npm install

      - save_cache:
          key: v1-dependencies-8.11.3-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: cd src && npm run build

      - persist_to_workspace:
          root: .
          paths:
            - dist

  lint:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: cd src && npm run lint

  unit-tests:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: cd src && npm run test

workflows:
  version: 2
  build-and-validate:
    jobs:
      - install-dependencies:
      - build:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
