export const ADD_DISC_TO_BAG = 'ADD_DISC_TO_BAG';
export const DISABLE_DISC = 'DISABLE_DISC';
export const ENABLE_DISC = 'ENABLE_DISC';
export const DISABLE_DISC_TYPE = 'DISABLE_DISC_TYPE';
export const ENABLE_DISC_TYPE = 'ENABLE_DISC_TYPE';
export const UPDATE_DISC_WEAR = 'UPDATE_DISC_WEAR';
export const REMOVE_DISC_FROM_BAG = 'REMOVE_DISC_FROM_BAG';

export const CHANGE_THROWER_TYPE = 'CHANGE_THROWER_TYPE';
export const CHANGE_THROWER_POWER = 'CHANGE_THROWER_POWER';

export const CHANGE_FAN_POWER = 'CHANGE_FAN_POWER';
export const CHANGE_PATHS = 'CHANGE_PATHS';
export const CHANGE_LIE_DISTANCE = 'CHANGE_LIE_DISTANCE';
export const CHANGE_LIE_CIRCLE = 'CHANGE_LIE_CIRCLE';
