export const SIMILARITY_CHANGE = 'SIMILARITY_CHANGE';
export const SIMILAR_SELECT_DISC = 'SIMILAR_SELECT_DISC';
export const SIMILAR_SET_SIMILAR_DISCS = 'SIMILAR_SET_SIMILAR_DISCS';
export const SIMILAR_CLEAR_SELECT_DISC = 'SIMILAR_CLEAR_SELECT_DISC';
export const SIMILAR_ENABLE_SELECT_DISC = 'SIMILAR_ENABLE_SELECT_DISC';
export const SIMILAR_ENABLE_SIMILAR_DISC = 'SIMILAR_ENABLE_SIMILAR_DISC';
