export const ADD_DISC_TO_BAG = 'ADD_DISC_TO_BAG';
export const ADD_DISC_TO_BAG_SUCCESS = 'ADD_DISC_TO_BAG_SUCCESS';
export const ADD_DISC_TO_BAG_FAILURE = 'ADD_DISC_TO_BAG_FAILURE';

export const UPDATE_DISC_WEAR = 'UPDATE_DISC_WEAR';
export const UPDATE_DISC_WEAR_SUCCESS = 'UPDATE_DISC_WEAR_SUCCESS';
export const UPDATE_DISC_WEAR_FAILURE = 'UPDATE_DISC_WEAR_FAILURE';

export const EDIT_DISC_WEIGHT = 'EDIT_DISC_WEIGHT';
export const EDIT_DISC_WEIGHT_SUCCESS = 'EDIT_DISC_WEIGHT_SUCCESS';
export const EDIT_DISC_WEIGHT_FAILURE = 'EDIT_DISC_WEIGHT_FAILURE';

export const EDIT_DISC_POWER = 'EDIT_DISC_POWER';
export const EDIT_DISC_POWER_SUCCESS = 'EDIT_DISC_POWER_SUCCESS';
export const EDIT_DISC_POWER_FAILURE = 'EDIT_DISC_POWER_FAILURE';

export const EDIT_DISC_THROW_TYPE = 'EDIT_DISC_THROW_TYPE';
export const EDIT_DISC_THROW_TYPE_SUCCESS = 'EDIT_DISC_THROW_TYPE_SUCCESS';
export const EDIT_DISC_THROW_TYPE_FAILURE = 'EDIT_DISC_THROW_TYPE_FAILURE';

export const EDIT_DISC_NAME = 'EDIT_DISC_NAME';
export const EDIT_DISC_NAME_SUCCESS = 'EDIT_DISC_NAME_SUCCESS';
export const EDIT_DISC_NAME_FAILURE = 'EDIT_DISC_NAME_FAILURE';

export const EDIT_DISC_ENABLED = 'EDIT_DISC_ENABLED';
export const EDIT_DISC_ENABLED_SUCCESS = 'EDIT_DISC_ENABLED_SUCCESS';
export const EDIT_DISC_ENABLED_FAILURE = 'EDIT_DISC_ENABLED_FAILURE';

export const EDIT_DISC_TYPE_ENABLED = 'EDIT_DISC_TYPE_ENABLED';
export const EDIT_DISC_TYPE_ENABLED_SUCCESS = 'EDIT_DISC_TYPE_ENABLED_SUCCESS';
export const EDIT_DISC_TYPE_ENABLED_FAILURE = 'EDIT_DISC_TYPE_ENABLED_FAILURE';

export const REMOVE_DISC_FROM_BAG = 'REMOVE_DISC_FROM_BAG';
export const REMOVE_DISC_FROM_BAG_SUCCESS = 'REMOVE_DISC_FROM_BAG_SUCCESS';
export const REMOVE_DISC_FROM_BAG_FAILURE = 'REMOVE_DISC_FROM_BAG_FAILURE';

export const IMPORT_BAGS_FROM_FILE = 'IMPORT_BAGS_FROM_FILE';

export const EXPORT_BAGS_TO_FILE = 'EXPORT_BAGS_TO_FILE';
export const EXPORT_BAGS_TO_FILE_SUCCESS = 'EXPORT_BAGS_TO_FILE_SUCCESS';
export const EXPORT_BAGS_TO_FILE_FAILURE = 'EXPORT_BAGS_TO_FILE_FAILURE';

export const SELECT_BAG = 'SELECT_BAG';
export const SELECT_BAG_SUCCESS = 'SELECT_BAG_SUCCESS';
export const SELECT_BAG_FAILURE = 'SELECT_BAG_FAILURE';

export const ADD_NEW_BAG_START = 'ADD_NEW_BAG_START';
export const ADD_NEW_BAG_FINISH = 'ADD_NEW_BAG_FINISH';
export const ADD_NEW_BAG_CANCEL = 'ADD_NEW_BAG_CANCEL';

export const ADD_NEW_BAG = 'ADD_NEW_BAG';
export const ADD_NEW_BAG_SUCCESS = 'ADD_NEW_BAG_SUCCESS';
export const ADD_NEW_BAG_FAILURE = 'ADD_NEW_BAG_FAILURE';

export const UPDATE_BAG_NAME_START = 'UPDATE_BAG_NAME_START';
export const UPDATE_BAG_NAME_FINISH = 'UPDATE_BAG_NAME_FINISH';
export const UPDATE_BAG_NAME_CANCEL = 'UPDATE_BAG_NAME_CANCEL';

export const EDIT_BAG_NAME = 'EDIT_BAG_NAME';
export const EDIT_BAG_NAME_SUCCESS = 'EDIT_BAG_NAME_SUCCESS';
export const EDIT_BAG_NAME_FAILURE = 'EDIT_BAG_NAME_FAILURE';

export const REMOVE_EXISTING_BAG = 'REMOVE_EXISTING_BAG';
export const REMOVE_EXISTING_BAG_SUCCESS = 'REMOVE_EXISTING_BAG_SUCCESS';
export const REMOVE_EXISTING_BAG_FAILURE = 'REMOVE_EXISTING_BAG_FAILURE';

export const OPEN_DISC_EDIT_MODAL = 'OPEN_DISC_EDIT_MODAL';
export const CLOSE_DISC_EDIT_MODAL = 'CLOSE_DISC_EDIT_MODAL';

export const ENLARG_MAP = 'ENLARGE_MAP';
export const SHRINK_MAP = 'SHRINK_MAP';
export const RESET_MAP = 'RESET_MAP';

export const CHECK_BAG_FOR_UPDATES = 'CHECK_BAG_FOR_UPDATES';
export const CHECK_BAG_FOR_UPDATES_SUCCESS = 'CHECK_BAG_FOR_UPDATES_SUCCESS';
export const CHECK_BAG_FOR_UPDATES_FAILURE = 'CHECK_BAG_FOR_UPDATES_FAILURE';
export const SET_MAP_THEME = 'SET_MAP_THEME';
