export const ADD_DISC_TO_BAG = 'ADD_DISC_TO_BAG';
export const DISABLE_DISC = 'DISABLE_DISC';
export const ENABLE_DISC = 'ENABLE_DISC';
export const DISABLE_DISC_TYPE = 'DISABLE_DISC_TYPE';
export const ENABLE_DISC_TYPE = 'ENABLE_DISC_TYPE';
export const UPDATE_DISC_WEAR = 'UPDATE_DISC_WEAR';
export const REMOVE_DISC_FROM_BAG = 'REMOVE_DISC_FROM_BAG';

export const IMPORT_BAGS_FROM_FILE = 'IMPORT_BAGS_FROM_FILE';
export const EXPORT_BAGS_TO_FILE = 'EXPORT_BAGS_TO_FILE';
export const SELECT_BAG = 'SELECT_BAG';
export const ADD_NEW_BAG_START = 'ADD_NEW_BAG_START';
export const ADD_NEW_BAG_FINISH = 'ADD_NEW_BAG_FINISH';
export const ADD_NEW_BAG_CANCEL = 'ADD_NEW_BAG_CANCEL';
export const UPDATE_BAG_NAME_START = 'UPDATE_BAG_NAME_START';
export const UPDATE_BAG_NAME_FINISH = 'UPDATE_BAG_NAME_FINISH';
export const UPDATE_BAG_NAME_CANCEL = 'UPDATE_BAG_NAME_CANCEL';
export const REMOVE_EXISTING_BAG = 'REMOVE_EXISTING_BAG';

export const OPEN_DISC_EDIT_MODAL = 'OPEN_DISC_EDIT_MODAL';
export const CLOSE_DISC_EDIT_MODAL = 'CLOSE_DISC_EDIT_MODAL';

export const EDIT_DISC_NAME = 'EDIT_DISC_NAME';
export const EDIT_DISC_WEIGHT = 'EDIT_DISC_WEIGHT';
export const EDIT_DISC_POWER = 'EDIT_DISC_POWER';
export const EDIT_DISC_THROW_TYPE = 'EDIT_DISC_THROW_TYPE';

export const ENLARG_MAP = 'ENLARGE_MAP';
export const SHRINK_MAP = 'SHRINK_MAP';
export const RESET_MAP = 'RESET_MAP';

export const CHECK_BAG_FOR_UPDATES = 'CHECK_BAG_FOR_UPDATES';
export const SET_MAP_THEME = 'SET_MAP_THEME';
