export const LOAD_COMPANY_DATA = 'LOAD_COMPANY_DATA';
export const LOAD_COMPANY_DATA_SUCCESS = 'LOAD_COMPANY_DATA_SUCCESS';
export const LOAD_COMPANY_DATA_FAILURE = 'LOAD_COMPANY_DATA_FAILURE';

export const SELECT_COMPANY_DISC = 'SELECT_COMPANY_DISC';
export const SELECT_COMPANY_DISC_SUCCESS = 'SELECT_COMPANY_DISC_SUCCESS';
export const SELECT_COMPANY_DISC_FAILURE = 'SELECT_COMPANY_DISC_FAILURE';
