export const CHANGE_FAN_POWER = 'CHANGE_FAN_POWER';
export const CHANGE_PATHS = 'CHANGE_PATHS';
export const CHANGE_LIE_DISTANCE = 'CHANGE_LIE_DISTANCE';
export const CHANGE_LIE_CIRCLE = 'CHANGE_LIE_CIRCLE';
