export const THROWER_OPEN_MODAL = 'THROWER_OPEN_MODAL';
export const THROWER_CLOSE_MODAL = 'THROWER_CLOSE_MODAL';

export const DISPLAY_OPTIONS_OPEN_MODAL = 'DISPLAY_OPTIONS_OPEN_MODAL';
export const DISPLAY_OPTIONS_CLOSE_MODAL = 'DISPLAY_OPTIONS_CLOSE_MODAL';

export const IMPORT_EXPORT_OPEN_MODAL = 'IMPORT_EXPORT_OPEN_MODAL';
export const IMPORT_EXPORT_CLOSE_MODAL = 'IMPORT_EXPORT_CLOSE_MODAL';
