export const SIMILARITY_CHANGE = 'SIMILARITY_CHANGE';
export const SIMILAR_SELECT_DISC = 'SIMILAR_SELECT_DISC';
export const SIMILAR_SET_SIMILAR_DISCS = 'SIMILAR_SET_SIMILAR_DISCS';
export const SIMILAR_CLEAR_SELECT_DISC = 'SIMILAR_CLEAR_SELECT_DISC';
export const SIMILAR_ENABLE_SELECT_DISC = 'SIMILAR_ENABLE_SELECT_DISC';
export const SIMILAR_ENABLE_SIMILAR_DISC = 'SIMILAR_ENABLE_SIMILAR_DISC';

export const SIMILAR_TOGGLE_SELECT_EDIT_MODAL = 'SIMILAR_OPEN_SELECT_EDIT_MODAL';
export const SIMILAR_EDIT_SELECT_WEIGHT = 'SIMILAR_EDIT_SELECT_WEIGHT';
export const SIMILAR_EDIT_SELECT_WEAR = 'SIMILAR_EDIT_SELECT_WEAR';
export const SIMILAR_EDIT_SELECT_POWER = 'SIMILAR_EDIT_SELECT_POWER';
