swagger: '2.0'

info:
  title: Common Supplier ACL Service
  description: An intermediary service to create and update the ICP layer data repository for the Common Supplier system
  version: 1.0.0

host: tbd

paths:
  /api/fulfillmentChannel/upsertMany:
    post:
      tags:
      - api
      - post
      summary: Takes an array of Fulfillment Channel data to insert or update documents in the ICP layer
      consumes:
      - application/json
      parameters:
        - in: body
          name: FulfillmentChannels
          description: An array of Fulfillment Channel objects to insert or upate in the ICP layer
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/FulfillmentChannel'
      responses:
        200:
          description: ICP layer was successfully updated with new or updated Fulfillment Channels
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: An error occurred during the inserting or updating documents
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/updateBrand:
    post:
      tags:
      - api
      - post
      summary: Takes the brand information for the Fulfillment Channel Object and updates them for the given object in the ICP layer
      consumes:
      - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          description: the Fulfillment Channel ID being updated
          required: true
          type: integer
        - name: Brand
          in: body
          description: the Brand information for a Fulfillment Channel
          required: true
          schema:
            $ref: '#/definitions/Brand'
      responses:
        200:
          description: Successfully updated the Fulfillment Channel Brand information in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in updating the Fulfillment Channel Brand information in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/updateContact:
    post:
      tags:
      - api
      - post
      summary: Takes the contact information for the Fulfillment Channel Object and updates it for the given object in the ICP layer
      consumes: 
      - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          description: the Fulfillment Channel ID being updated
          required: true
          type: integer
        - name: Contact
          in: body
          description: The Contact information for a Fulfillment Channel
          required: true
          schema:
            $ref: '#/definitions/Contact'
      responses:
        200:
          description: Successfully updated the Fulfillment Channel Contact information in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in updating the Fulfillment Channel Contact infortmation in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/assignSalesChannels:
    post:
      tags:
      - api
      - post
      summary: Adds an array of assigned Sales Channels, by ID, to the ICP layer for a specific Fulfillment Channel
      consumes:
      - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          required: true
          description: The Fulfillment Channel ID being updated
          type: integer
        - name: SalesChannels
          in: body
          description: An array of Sales Channels, by ID, to add to an existing Fulfillment Channel in the ICP layer
          required: true
          schema:
            $ref: '#/definitions/SalesChannels'
      responses:
        200:
          description: Succesfully added the Sales Channels for a given Fulfillment Channel in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in adding the Fulfillment Channel with the Sales Channels in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/unassignSalesChannels:
    delete:
      tags:
      - api
      - delete
      summary: Removes all the Sales Channels, by ID, passed in an array, from the ICP layer for a specific Fulfillment Channel
      consumes:
        - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          required: true
          description: The Fulfillment Channel ID being updated
          type: integer
        - name: SalesChannels
          in: body
          description: An array of Sales Channels, by ID, to remove from an existing Fulfillment Channel in the ICP layer
          required: true
          schema:
            $ref: '#/definitions/SalesChannels'
      responses:
        200:
          description: Successfully removed the Sales Channels for a given Fulfillment Channel in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in removing the Sales Channels from a given Fulfillment Channel in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/assignDepartments:
    post:
      tags:
      - api
      - post
      summary: Adds an array of Departments, by ID, to the ICP layer for a specific Fulfillment Channel
      consumes:
      - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          required: true
          description: The Fulfillment Channel ID being updated
          type: integer
        - name: Departments
          in: body
          description: An array of Departments, by ID, to remove from an existing Fulfillment Channel in the ICP layer
          required: true
          schema:
            $ref: '#/definitions/Departments'
      responses:
        200:
          description: Successfully removed the Departments for a given Fulfillment Channel in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in removing the Departments from a given Fulfillment Channel inf the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}/unassignDepartments:
    delete:
      tags:
      - api
      - delete
      summary: Removes an array of Departments, by ID, to the ICP layer for a specific Fulfillment Channel
      consumes:
      - application/json
      parameters:
        - name: fulfillmentChannelId
          in: path
          required: true
          description: The Fulfillment Channel ID being updated
          type: integer
        - name: Departments
          in: body
          description: An array of Departments, by ID, to add to an existing Fulfillment Channel in the ICP layer
          required: true
          schema:
            $ref: '#/definitions/Departments'
      responses:
        200:
          description: Successfully added the Departments for a given Fulfillment Channel in the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: Failed in added the Departments from a given Fulfillment Channel inf the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
  /api/fulfillmentChannel/{fulfillmentChannelId}:
    delete:
      tags:
      - api
      - delete
      summary: Removes a FulfillmentChannel from the ICP layer based on the FulfillmentChannelId
      parameters:
        - in: path
          name: fulfillmentChannelId
          description: The FulfillmentChannelId of the FulfillmentChannel to remove from the ICP layer
          required: true
          type: integer
      responses:
        200:
          description: Successfully deleted the FulfillmentChannel from the ICP layer
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: An error occured while trying to delete the FulfillmentChannel from the ICP layer
  /status/ready:
    get:
      tags:
      - status
      - get
      summary: A status ready check returns okay if the system is ready for use
      responses:
        200:
          description: System is up and running and ready for processing
          schema:
            $ref: '#/definitions/ObjectResult'
        404:
          description: System is not up, so this endpoint won't even be found
  /status/health:
    get:
      tags:
      - status
      - get
      summary: a status health check to make sure that the index exists, and creates it if it doesn't and returns successful if the service is in a healthy state
      responses:
        200:
          description: System is healthy, index exists, and there were no errors checking it
          schema:
            $ref: '#/definitions/ObjectResult'
        500:
          description: System is not healthy, there was an issue with the index or with creating the index and the system is not in a healthy state
          schema:
            $ref: '#/definitions/ObjectResult'
definitions:
  FulfillmentChannel:
    type: object
    properties:
      FulfillmentChannelId:
        type: integer
      BrandName:
        type: string
      BrandLogoUrl: 
        type: string
      ContactName:
        type: string
      ContactPhone:
        type: string
      ContactPhoneExtension:
        type: string
      ContactFax:
        type: string
      ContactFaxExtension:
        type: string
      ContactEmail:
        type: string
      AddressLine1:
        type: string
      AddressLine2: 
        type: string
      City:
        type: string
      State:
        type: string
      ZipCode:
        type: string
      SalesChannelIds:
        type: array
        items: 
          type: integer
      Departments:
        type: array
        items:
          type: integer
  Brand:
    type: object
    properties:
      Name:
        type: string
      LogoUrl:
        type: string
  Contact:
    type: object
    properties:
      Name:
        type: string
      Phone:
        type: string
      PhoneExtension:
        type: string
      Fax:
        type: string
      FaxExtension:
        type: string
      Email:
        type: string
      AddressLine1:
        type: string
      AddressLine2: 
        type: string
      City:
        type: string
      State:
        type: string
      ZipCode:
        type: string
  SalesChannels:
    type: array
    items:
      type: integer
  Departments:
    type: array
    items:
      type: integer
  ObjectResult:
    type: object
    properties:
      StatusCode:
        type: integer
        example: 200
      Value:
        type: string
        example: "Index Created"
